"""Meteor shower catalog: the ~38 showers on the IMO's Working List of
Visual Meteor Showers.

Names, IAU numbers/codes, radiant positions, activity (solar longitude of
peak), ZHR, and population index are transcribed from the International
Meteor Organization's Meteor Shower Calendar, Table 5 -- see
scripts/build_shower_catalog.py's docstring for the exact edition and
transcription notes. Citation (IMO's usual practice for this data):

    Molau, S.; Barentsen, G.; Crivello, S.; et al., International Meteor
    Organization, Meteor Shower Calendar. https://www.imo.net/

Parent bodies are cross-referenced from the IAU Meteor Data Center
(Commission F1), https://www.iaumeteordatacenter.org/, whose citation
request asks work using it to cite:
  Jenniskens, P.; Jopek, T.J.; Janches, D.; Hajdukova, M.; Kokhirova, G.I.;
    Rudawska, R.; 2020, Planetary and Space Science, Vol. 182, 104821.
  Jopek, T.J.; Kanuchova, Z.; 2017, Planetary and Space Science, 143, 3-6.

The data itself lives in data/shower_catalog.csv, generated by
scripts/build_shower_catalog.py -- edit that script's IMO_WORKING_LIST /
GMN_DECAY_RATES tables, not the CSV, and rerun it.

Neither IMO's calendar nor the IAU MDC publishes activity decay rates
(how fast ZHR rises/falls around peak), so a rate estimate is only
possible for a shower with all of ZHR, population index, AND decay-rate
data -- see ShowerDef.has_rate_data. Real decay rates, for 21 showers
with a credible per-shower fit, come from the Global Meteor Network's
operational flux-monitoring data (github.com/CroatianMeteorNetwork/RMS,
share/flux_showers.csv) -- see scripts/build_shower_catalog.py's
docstring for the exact file section and citation.

Radiant RA/Dec are fixed at their peak-epoch position (not drift-corrected
day by day) -- adequate for judging whether a radiant is above the horizon
on a given night, per the daily radiant drift these showers exhibit
(typically well under 1 degree/day).
"""

from __future__ import annotations

import re
from dataclasses import dataclass


@dataclass(frozen=True)
class ShowerDef:
    name: str
    iau_code: str  # IAU Meteor Data Center 3-letter code, e.g. "PER"
    iau_number: int
    radiant_ra_deg: float  # J2000, decimal degrees
    radiant_dec_deg: float  # J2000, decimal degrees
    peak_month: int
    peak_day: int
    peak_hour_utc: float
    parent_body: str | None
    peak_zhr: float | None = None
    population_index: float | None = None
    b_rise: float | None = None
    b_decline: float | None = None

    @property
    def has_rate_data(self) -> bool:
        """False if any of ZHR/population-index/decay-rate is missing --
        a rate estimate needs all four, not just a ZHR (see catalog.py's
        module docstring: most IMO-listed showers have a real ZHR but no
        published decay rate).
        """
        return None not in (self.peak_zhr, self.population_index, self.b_rise, self.b_decline)


SHOWERS: list[ShowerDef] = []  # populated below by _load()


def _load() -> list[ShowerDef]:
    from importlib import resources

    import csv

    path = resources.files(__package__) / "data" / "shower_catalog.csv"
    showers = []
    with path.open(newline="", encoding="utf-8") as f:
        for row in csv.DictReader(f):
            showers.append(
                ShowerDef(
                    name=row["name"],
                    iau_code=row["iau_code"],
                    iau_number=int(row["iau_number"]),
                    radiant_ra_deg=float(row["radiant_ra_deg"]),
                    radiant_dec_deg=float(row["radiant_dec_deg"]),
                    peak_month=int(row["peak_month"]),
                    peak_day=int(row["peak_day"]),
                    peak_hour_utc=float(row["peak_hour_utc"]),
                    parent_body=row["parent_body"] or None,
                    peak_zhr=float(row["peak_zhr"]) if row["peak_zhr"] else None,
                    population_index=float(row["population_index"]) if row["population_index"] else None,
                    b_rise=float(row["b_rise"]) if row["b_rise"] else None,
                    b_decline=float(row["b_decline"]) if row["b_decline"] else None,
                )
            )
    return showers


SHOWERS = _load()


def _normalize(s: str) -> str:
    return re.sub(r"[-\s]+", " ", s.strip().lower())


def find_shower(name: str) -> ShowerDef:
    """Look up a shower by (in order): exact IAU code, exact name, unambiguous
    name prefix, or unambiguous substring (hyphen/space-insensitive, so e.g.
    "Delta Aquariids" matches "Southern delta-Aquariids").
    """
    needle = name.strip().lower()

    for s in SHOWERS:
        if s.iau_code.lower() == needle:
            return s
    for s in SHOWERS:
        if s.name.lower() == needle:
            return s

    prefix_matches = [s for s in SHOWERS if s.name.lower().startswith(needle)]
    if len(prefix_matches) == 1:
        return prefix_matches[0]

    norm_needle = _normalize(name)
    substr_matches = [s for s in SHOWERS if norm_needle in _normalize(s.name)]
    if len(substr_matches) == 1:
        return substr_matches[0]

    candidates = {s.name: s for s in (*prefix_matches, *substr_matches)}
    if len(candidates) > 1:
        raise ValueError(f"Ambiguous shower name {name!r}; matches: {', '.join(sorted(candidates))}")
    raise ValueError(f"Unknown meteor shower {name!r}. Try --list-showers, or an IAU code like 'PER'.")
